# Test your FastAPI endpoints

###
# curl http://127.0.0.1:8000
GET http://127.0.0.1:8000
Accept: application/json

###
# http://127.0.0.1:8000/docs
GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
